CREATE DATABASE HR_ANALYTICS;
USE HR_ANALYTICS;

CREATE TABLE EMPLOYEE_DATA(
EMPLOYEE_ID INT PRIMARY KEY,
NAME VARCHAR(20),
GENDER VARCHAR(10),
DEPARTMENT VARCHAR (20),
JOB_ROLE VARCHAR (20),
SALARY INT,
 EXPERIENCE INT, 
ATTRITION VARCHAR (10),
SATISFACTION INT ,
JOINING_DATE DATE 
);
SELECT * FROM EMPLOYEE_DATA;

SELECT COUNT(*) AS TOTAL_EMPLOYESS
FROM EMPLOYEE_DATA;

SELECT GENDER,
COUNT(*)AS EMPLOYEE_COUNT 
FROM EMPLOYEE_DATA
GROUP BY GENDER;

SELECT DEPARTMENT,
COUNT(*)AS TOTAL_EMPLOYEE
FROM EMPLOYEE_DATA
GROUP BY DEPARTMENT;

SELECT AVG(SALARY) AS AVERAGE_SALARY
FROM EMPLOYEE_DATA;

SELECT NAME, SALARY
FROM EMPLOYEE_DATA
ORDER BY SALARY DESC
LIMIT 1;

SELECT ATTRITION,
COUNT(*)AS EMPLOYEE_COUNT
FROM EMPLOYEE_DATA
GROUP BY ATTRITION;

SELECT DEPARTMENT,
COUNT(*)AS ATTRITION_COUNT 
FROM EMPLOYEE_DATA
WHERE ATTRITION = "YES"
GROUP BY DEPARTMENT;

SELECT DEPARTMENT, 
AVG(SALARY) AS AVERAGE_SALARY
FROM EMPLOYEE_DATA
GROUP BY DEPARTMENT ;

SELECT NAME, DEPARTMENT, SALARY
FROM EMPLOYEE_DATA 
ORDER BY SALARY DESC
LIMIT 5;

SELECT SATISFACTION,
count(*) AS EMPLOYEE_COUNT
FROM EMPLOYEE_DATA
GROUP BY SATISFACTION
ORDER BY SATISFACTION ;

SELECT DEPARTMENT, 
AVG(SATISFACTION) AS AVERAGE_SATISFACTION
FROM EMPLOYEE_DATA
GROUP BY DEPARTMENT
ORDER BY DEPARTMENT ASC
LIMIT 1;


SELECT YEAR (JOINING_DATE) AS JOINING_YEAR,
COUNT(*) AS EMPLOYED_HIRED
FROM EMPLOYEE_DATA
GROUP BY YEAR (JOINING_DATE)
ORDER BY 	JOINING_YEAR ;

SELECT NAME, DEPARTMENT, JOINING_DATE
FROM EMPLOYEE_DATA
ORDER BY JOINING_DATE DESC
LIMIT 10;

SELECT DEPARTMENT,
COUNT(*) AS TOTAL_EMPLOYEES
FROM EMPLOYEE_DATA
GROUP BY DEPARTMENT 
ORDER BY TOTAL_EMPLOYEES DESC
LIMIT 1;

SELECT DEPARTMENT,
AVG(SALARY) AS AVERAGE_SALARY
FROM EMPLOYEE_DATA
GROUP BY DEPARTMENT 
ORDER BY AVERAGE_SALARY DESC
LIMIT 1;

SELECT AVG(EXPERIENCE) AS AVERAGE_EXPERIENCE
FROM EMPLOYEE_DATA;

SELECT NAME, DEPARTMENT,EXPERIENCE
FROM EMPLOYEE_DATA 
ORDER BY EXPERIENCE DESC
LIMIT 10;

SELECT NAME, DEPARTMENT, SALARY 
FROM EMPLOYEE_DATA 
WHERE SALARY >
 ( SELECT AVG(SALARY)
 FROM EMPLOYEE_DATA
 );
 
 SELECT NAME, DEPARTMENT, SATISFACTION 
 FROM EMPLOYEE_DATA 
 WHERE SATISFACTION < 3;
 
 SELECT 
ROUND(
(COUNT(CASE WHEN Attrition='Yes' THEN 1 END) * 100.0)
/ COUNT(*),2
) AS Attrition_Percentage
FROM employee_data;
